// src/components/IngredientList.vue
<script setup lang="ts">
import type { Ingredient } from '@/types/recipe'
import { formatIngredientAmount } from '@/utils/recipeFormat'

const { ingredients } = defineProps<{
  ingredients: Ingredient[]
}>()
</script>

<template>
  <section class="ingredient-list">
    <h2 class="ingredient-list__heading">Ingredients</h2>
    <ul class="ingredient-list__items">
      <li
        v-for="(ingredient, index) in ingredients"
        :key="index"
        class="ingredient-list__item list-row-divider list-row-divider--padded"
        :class="{ 'list-row-divider--flush-top': index === 0 }"
      >
        <span class="ingredient-list__name">{{ ingredient.name }}</span>
        <span class="ingredient-list__amount">
          {{ formatIngredientAmount(ingredient.amount, ingredient.unit) }}
        </span>
      </li>
    </ul>
  </section>
</template>

<style scoped>
.ingredient-list__heading {
  margin: 0 0 0.875rem;
  font-size: var(--font-size-base);
  font-weight: 700;
  color: var(--color-text);
}

.ingredient-list__items {
  list-style: none;
  margin: 0;
  padding: 0;
}

.ingredient-list__item {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  gap: 1rem;
  font-size: var(--font-size-base);
}

.ingredient-list__name {
  color: var(--color-text);
}

.ingredient-list__amount {
  color: var(--color-text);
  flex-shrink: 0;
}
</style>

// src/components/IngredientList/index.tsx
import type { Ingredient } from '@/types/recipe'
import { formatIngredientAmount } from '@/utils/recipeFormat'

import './IngredientList.css'

type IngredientListProps = {
  ingredients: Ingredient[]
}

export function IngredientList({ ingredients }: IngredientListProps): React.ReactElement {
  return (
    <section className="ingredient-list">
      <h2 className="ingredient-list__heading">Ingredients</h2>
      <ul className="ingredient-list__items">
        {ingredients.map((ingredient, index) => (
          <li
            key={`${ingredient.name}-${index}`}
            className={`ingredient-list__item list-row-divider list-row-divider--padded${
              index === 0 ? ' list-row-divider--flush-top' : ''
            }`}
          >
            <span className="ingredient-list__name">{ingredient.name}</span>
            <span className="ingredient-list__amount">
              {formatIngredientAmount(ingredient.amount, ingredient.unit)}
            </span>
          </li>
        ))}
      </ul>
    </section>
  )
}
